# Generated by Django 4.2.4 on 2023-08-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos_func_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
